import productImage1 from '../assets/image/book.jpg';
import productImage2 from '../assets/image/book2.jpg';
import productImage3 from '../assets/image/book3.jpg';
import productImage4 from '../assets/image/book4.jpg';
import productImage5 from '../assets/image/book5.jpg';
import productImage6 from '../assets/image/book6.jpg';

// Add more images as needed

export const product1 = [
  {
    id: 1,
    image: productImage2,
    title: 'The Hunger Games Trilogy  ',
    author:'Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 2,
    image: productImage6,
    title: 'The Hunger Games Trilogy  ',
    author:'Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 3,
    image: productImage3,
    title: 'The Hunger Games Trilogy',
    author:' Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 4,
    image: productImage4,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  // More products...
];

export const product2 = [
  {
    id: 5,
    image: productImage5,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 6,
    image: productImage6,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 7,
    image: productImage4,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 8,
    image: productImage4,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 9,
    image: productImage4,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
  {
    id: 10,
    image: productImage4,
    title: 'The Hunger Games Trilogy 3 Book Set by Suzanne Collins',
    description: `The extraordinary, groundbreaking New York Times bestsellers The Hunger Games and Catching Fire, along with the third book in The Hunger Games trilogy by Suzanne Collins, Mockingjay, are available for the first time ever in a beautiful boxset edition. Stunning, gripping, and engaging storytelling makes this trilogy a must-read for any fan of dystopian fiction.`,
    rate: 699,
    oldPrice: 999,
    discount: 'Save 30%',
    binding: 'Paperback',
    condition: 'New',
    delivery: 'Delivery within 6-8 business days',
    qualityCheck: 'Original Books',
    bookmark: 'Free Bookmarks',
    inStock: true,
    rating: 5,
  },
];

export const product3 = [
  {
    id: 11,
    image: productImage2,
    title: 'You Are My Best Wife',
    description: 'rating',
    price: 500,
  },
  {
    id: 12,
    image: productImage1,
    title: 'You Are My Best Wife',
    description: 'rating',
    price: 500,
  },
  {
    id: 13,
    image: productImage1,
    title: 'You Are My Best Wife',
    description: 'rating',
    price: 500,
  },
  {
    id: 14,
    image: productImage1,
    title: 'You Are My Best Wife',
    description: 'rating',
    price: 500,
  },
  {
    id: 15,
    image: productImage1,
    title: 'You Are My Best Wife.',
    description: 'rating',
    price: 500,
  },
  {
    id: 16,
    image: productImage1,
    title: 'You Are My Best Wife.',
    description: 'rating',
    price: 500,
  },
];
